name: 'Deploy to Prod'

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: website
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
          cache-dependency-path: website/package-lock.json
      - name: Deploy
        run: npm deploy