name: 'Deploy to Prod'

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: website
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
          cache-dependency-path: website/package-lock.json
      - name: Install
        run: npm install
      - run : git config user.email github-actions@github.com
      - run : git config user.name github-actions
      - name: Deploy
        run: npm run build
      - run : git --work-tree build add --all
      - run : git commit -m "Automatic Deploy action run by github-actions"
      - run : git push origin HEAD:gh-pages --force